### ISSUE TITLE
ID1727 the recommended status cannot be achieved

### ISSUE THREAD

**Issue by Rxcmoon** [0x6d69636b/windows_hardening#53]
Hi,

if I set to Download Mode to Disabled as recommended in my GPO the result is
"ID 1727, Delivery Optimization: Download Mode, Result=3, Recommended=, Severity=Medium"

I also have try all settings (0), (1), (2), (3), (99), (100)
The status "Recommended=," cannot be reached with any setting.

My research has shown that the optimal setting is "99", simple download mode without peering.
2pintsoftware seems to be legitimate and professional in their knowledge and understanding.
https://2pintsoftware.com/delivery-optimization-dl-mode/

**Comment by 0x6d69636b** [comment]
Thank you for spotting this bug. The reason for this is that ID 1727 has a DefaultValue of 3, so if the registry key is not set HardeningKitty assumes that the default behaviour kicks it and uses the value 3. :( 

I checked [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization-reference) and noticed that the DefaultValue in fact is 1 - I will change that. Additionally I'll update my recommendation to 99 (same as BSI SiSyPHuS). Fixed in commit https://github.com/0x6d69636b/windows_hardening/commit/7aade83fa8d80a1ff39667439658849260ecd44a
