### ISSUE TITLE
Awesome tool, any plans to extend this to support edge chromium, etc..?

### ISSUE THREAD

**Issue by c3rberus** [0x6d69636b/windows_hardening#7]
This is a great tool, much easier to digest the information printed out in audit mode than it is to use the Policy Analyzer, great work.

Any plans to extend this to support Edge Chromium baselines and Windows Server (member/dc) using latest baselines?

**Comment by 0x6d69636b** [comment]
Thanks a lot for your feedback! :-)

The default list [finding_list_0x6d69636b_machine](https://github.com/0x6d69636b/windows_hardening/blob/master/lists/finding_list_0x6d69636b_machine.csv) should cover most settings for clients, member server and domain controllers. But it would also be possible to define a separate list for each category - honestly, I was reluctant to do that because of the maintenance effort.

As for Microsoft Edge/Chromium, I reviewed the last baseline, they are all registry settings, this makes it very easy to build a finding list. As a first step I have now implemented the 12 recommendations from Microsoft: [finding_list_msft_edge_machine](https://github.com/0x6d69636b/windows_hardening/blob/master/lists/finding_list_msft_edge_machine.csv).

**Comment by 0x6d69636b** [comment]
I have extended the finding lists with the Microsoft Security Baseline and now also cover Internet Explorer settings.
