### ISSUE TITLE
New registry locations for ID 1631, Group Policy: Process even if...

### ISSUE THREAD

**Issue by exceedio** [0x6d69636b/windows_hardening#89]
I see that ID **1631** in **finding_list_0x6d69636b_machine.csv** is looking for a registry policy at:

HKLM:\Software\Policies\Microsoft\Windows\Group Policy\\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}

It seems that more recent versions of Windows 10 (and probably 11) have broken this out in to two different policies for wired and wireless.  On my Windows 10 Ent 21H2 test machine they are at:

HKLM:\SOFTWARE\Policies\Microsoft\Windows\Group Policy\\{0ACDD40C-75AC-47ab-BAA0-BF6DE7E7FE63}
HKLM:\SOFTWARE\Policies\Microsoft\Windows\Group Policy\\{B587E2B1-4D59-4e7e-AED9-22B9DF11D053}

The values are written to the above registry keys when set via Group Policy and as a result they get flagged as failed on version 0.7.0 of the hardening script.

Not sure exactly how this could get handled but I'm very impressed with your work and find it immensely useful.

**Comment by 0x6d69636b** [comment]
Thank you for the nice words and for creating this issue.

As far as I know these are different policies, which exist since Windows 2000 / Vista:
- [Configure wired policy processing](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.GroupPolicy::CSE_Wired)
- [Configure wireless policy processing](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.GroupPolicy::CSE_Wireless)

These policies manage how network related settings are updated but should not have impact how group policies updates are managed. I tested ID 1631 on a Windows 10 Pro 21H2 and the registry path is still valid. Do you have additional information or could upload your configuration?

![gpo_policy_setting-01](https://user-images.githubusercontent.com/13913706/167061116-f1a5d881-6aa1-479f-a54d-725fb23769ba.png)

**Comment by 0x6d69636b** [comment]
Thank you for the update :+1:
